version: '3.4'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: BeyondShoppingDB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
     - "5437:5432"

  beyondshopping.host:
    image: ${DOCKER_REGISTRY-}beyondshoppinghost
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_HTTP_PORTS=8070
      - ASPNETCORE_HTTPS_PORTS=8071
      - ASPNETCORE_Kestrel__Certificates__Default__Password=B>9S7Cxp85u-
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    build:
      context: .
      dockerfile: src/BeyondShopping.Host/Dockerfile
    depends_on:
      - db
    ports:
     - "8090:8070"
     - "8091:8071"
    volumes:
      - ${USERPROFILE}/.aspnet/https:/https/
